import {
  LayoutDashboard,
  Package,
  Boxes,
  ArrowLeftRight,
  ClipboardList,
  User,
  Truck,
  Building2,
  BookOpen,
  FileBarChart2,
  ShoppingCart,
  PackageCheck,
  RotateCcw,
  ShieldCheck,
  History,
  FileText,
  Factory,
  KeyRound,
} from 'lucide-react';

export const appRoutes = [
  { path: '/', label: 'Dashboard', icon: LayoutDashboard, allPermissions: ['dashboard.view'] },
  { path: '/products', label: 'Products', icon: Package, allPermissions: ['products.view'] },
  { path: '/categories', label: 'Categories', icon: Boxes, allPermissions: ['categories.view'] },
  { path: '/movements', label: 'Stock Movements', icon: ArrowLeftRight, allPermissions: ['inventory.view'] },
  { path: '/suppliers', label: 'Suppliers', icon: Building2, allPermissions: ['suppliers.view'] },
  { path: '/purchases', label: 'Purchases', icon: Truck, allPermissions: ['purchases.view'] },
  { path: '/purchase-requisitions', label: 'Purchase Requisitions', icon: ClipboardList, allPermissions: ['purchase_requisitions.view'] },
  { path: '/goods-receipts', label: 'Goods Receipts', icon: PackageCheck, allPermissions: ['goods_receipts.view'] },
  { path: '/sales', label: 'Sales', icon: ShoppingCart, allPermissions: ['sales.view'] },
  { path: '/deliveries', label: 'Deliveries', icon: PackageCheck, allPermissions: ['deliveries.view'] },
  { path: '/sales-returns', label: 'Sales Returns', icon: RotateCcw, allPermissions: ['sales_returns.view'] },
  { path: '/sales-orders', label: 'Sales Orders', icon: FileText, allPermissions: ['sales_orders.view'] },
  { path: '/accounting', label: 'Accounting', icon: BookOpen, allPermissions: ['accounting.view'] },
  { path: '/financial-reports', label: 'Financial Reports', icon: FileBarChart2, allPermissions: ['financial_reports.view'] },
  { path: '/mrp', label: 'MRP / Replenishment', icon: Factory, allPermissions: ['mrp.view'] },
  { path: '/reports', label: 'Reports', icon: ClipboardList, allPermissions: ['inventory.view'] },
  { path: '/accounting-periods', label: 'Accounting Periods', icon: FileText, allPermissions: ['accounting_periods.view'] },
  { path: '/users', label: 'Users', icon: User, allPermissions: ['users.view'] },
  { path: '/access-control', label: 'Access Control', icon: KeyRound, allPermissions: ['roles.manage'] },
  { path: '/audit-trail', label: 'Audit Trail', icon: History, allPermissions: ['audit_trails.view'] },
  { path: '/customer-refunds', label: 'Customer Refunds', icon: ShieldCheck, allPermissions: ['customer_refunds.view'] },
];
