import {
  LayoutDashboard,
  Package,
  Tags,
  ArrowLeftRight,
  FileText,
  ShoppingCart,
  Truck,
  Receipt,
  BarChart3,
  Users,
  ShieldCheck,
  ClipboardList,
  Boxes,
  RotateCcw,
  Wallet,
  CalendarDays,
  Factory,
} from 'lucide-react';

export const appRoutes = [
  {
    path: '/',
    label: 'Dashboard',
    icon: LayoutDashboard,
    allPermissions: ['dashboard.view'],
  },
  {
    path: '/products',
    label: 'Products',
    icon: Package,
    allPermissions: ['products.view'],
  },
  {
    path: '/categories',
    label: 'Categories',
    icon: Tags,
    allPermissions: ['categories.view'],
  },
  {
    path: '/movements',
    label: 'Movements',
    icon: ArrowLeftRight,
    allPermissions: ['inventory.view'],
  },
  {
    path: '/reports',
    label: 'Reports',
    icon: FileText,
    anyPermissions: ['financial_reports.view', 'inventory.view', 'dashboard.view'],
  },
  {
    path: '/purchases',
    label: 'Purchases',
    icon: ShoppingCart,
    allPermissions: ['purchases.view'],
  },
  {
    path: '/purchase-requisitions',
    label: 'Purchase Requisitions',
    icon: ClipboardList,
    allPermissions: ['purchase_requisitions.view'],
  },
  {
    path: '/suppliers',
    label: 'Suppliers',
    icon: Truck,
    allPermissions: ['suppliers.view'],
  },
  {
    path: '/sales',
    label: 'Sales',
    icon: Receipt,
    allPermissions: ['sales.view'],
  },
  {
    path: '/deliveries',
    label: 'Deliveries',
    icon: Truck,
    allPermissions: ['deliveries.view'],
  },
  {
    path: '/sales-returns',
    label: 'Sales Returns',
    icon: RotateCcw,
    allPermissions: ['sales_returns.view'],
  },
  {
    path: '/sales-orders',
    label: 'Sales Orders',
    icon: ClipboardList,
    allPermissions: ['sales_orders.view'],
  },
  {
    path: '/goods-receipts',
    label: 'Goods Receipts',
    icon: Boxes,
    allPermissions: ['goods_receipts.view'],
  },
  {
    path: '/accounting-periods',
    label: 'Accounting Periods',
    icon: CalendarDays,
    allPermissions: ['accounting_periods.view'],
  },
  {
    path: '/accounting',
    label: 'Accounting',
    icon: Wallet,
    allPermissions: ['accounting.view'],
  },
  {
    path: '/financial-reports',
    label: 'Financial Reports',
    icon: BarChart3,
    allPermissions: ['financial_reports.view'],
  },
  {
    path: '/customer-refunds',
    label: 'Customer Refunds',
    icon: RotateCcw,
    allPermissions: ['customer_refunds.view'],
  },
  {
    path: '/audit-trail',
    label: 'Audit Trail',
    icon: FileText,
    allPermissions: ['audit_trails.view'],
  },
  {
    path: '/mrp',
    label: 'MRP Planning',
    icon: Factory,
    allPermissions: ['mrp.view'],
  },
  {
    path: '/users',
    label: 'Users',
    icon: Users,
    allPermissions: ['users.view'],
  },
  {
    path: '/access-control',
    label: 'Access Control',
    icon: ShieldCheck,
    allPermissions: ['roles.manage'],
  },
];