export async function createInventoryMovement(connection, payload) {
  const {
    movement_date,
    product_id,
    warehouse_id,
    reference_type,
    reference_id,
    reference_line_id,
    movement_type,
    direction,
    requested_uom_code,
    base_uom_code,
    conversion_factor,
    requested_quantity,
    base_quantity,
    unit_cost,
    total_cost,
    lot_number,
    expiry_date,
    serial_numbers_json,
    scope,
  } = payload;

  await connection.query(
    `
    INSERT INTO inventory_movements (
      movement_date,
      product_id,
      warehouse_id,
      reference_type,
      reference_id,
      reference_line_id,
      movement_type,
      direction,
      requested_uom_code,
      base_uom_code,
      conversion_factor,
      requested_quantity,
      base_quantity,
      unit_cost,
      total_cost,
      lot_number,
      expiry_date,
      serial_numbers_json,
      company_id,
      branch_id,
      business_unit_id
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `,
    [
      movement_date,
      product_id,
      warehouse_id,
      reference_type,
      reference_id,
      reference_line_id || null,
      movement_type,
      direction,
      requested_uom_code || null,
      base_uom_code,
      Number(conversion_factor || 1),
      Number(requested_quantity || 0),
      Number(base_quantity || 0),
      Number(unit_cost || 0),
      Number(total_cost || 0),
      lot_number || null,
      expiry_date || null,
      JSON.stringify(serial_numbers_json || []),
      scope?.company_id || null,
      scope?.branch_id || null,
      scope?.business_unit_id || null,
    ]
  );
}